# Train-Test split of Housing

#### Goal:

Splitting our dataset in differents part for having results for our Auto-ML models more comparable

Importing our already treated data set

In [2]:
import pandas as pd
df = pd.read_csv("no_string_no_nan.csv")
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,0,0,0,0,0,0,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,0,0,0,0,0,0,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,0,0,0,0,0,0,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,1,1,0,0,0,0,0,0,0,1
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,0,0,0,0,0,0,0

Splitting of our data set in "train" and "test" with a 33% ratio

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

train,test = train_test_split(df,test_size=0.33)

Splitting "train" and "test" in "X" and "y". 
- X having the features 
- y having the target

In [6]:
X_train = train.drop("SalePrice",axis=1)
X_test = test.drop("SalePrice",axis=1)

y_train = train
for col in train.columns:
    if col != "SalePrice":
        y_train = y_train.drop(col,axis=1)

y_test = test
for col in test.columns:
    if col != "SalePrice":
        y_test = y_test.drop(col,axis=1)

Exporting the created sub-datasets

In [11]:
X_train.to_csv("processed/x_train.csv",index=False)
y_train.to_csv("processed/y_train.csv",index=False)
X_test.to_csv("processed/x_test.csv",index=False)
y_test.to_csv("processed/y_test.csv",index=False)
train.to_csv("processed/train.csv",index=False)
test.to_csv("processed/test.csv",index=False)